#!/bin/sh
# File generated by ocamlbuild

cd '/home/josselin/Documents/Info/Syst Dig/Projet/simulateur'

rm -f netlist_ast.cmi
rm -f netlist_ast.cmo
# Also clean the script itself
rm -f '/home/josselin/Documents/Info/Syst Dig/Projet/simulateur/_build/sanitize.sh'
